FORMAT: X-1A
HOST: http://www.google.com/

# H2O REST API
Documentation of H2O REST API.

## Inspect [/Inspect{id}]
The following section describes Inspect REST call.

+ Parameters
  + id (number) ... unique identifier

### Retrieve [GET]
+ Request
    ahoj  
+ Response 200 (application/json)
    { "message": "All your base are belong to us." }
